name: Release

on:
  release:
    types: [ published ]
  push:
    tags:
      - 'Mu-Proton-*-*'

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - name: ${{ github.ref_name }}-x86_64
            cflags: -O3 -march=nocona -mtune=core-avx2
            rustflags: -Copt-level=3 -Ctarget-cpu=nocona -Ccodegen-units=1

          - name: ${{ github.ref_name }}-x86_64_v3
            cflags: -O3 -march=haswell -mno-rdrnd --param=l1-cache-size=32 --param=avoid-fma-max-bits=128
            rustflags: -Copt-level=3 -Ctarget-cpu=haswell -Ctarget-feature=-rdrand -Ccodegen-units=1

          - name: ${{ github.ref_name }}-arm64
            configure: >-
              --without-nvidia-libs
              --target-arch=arm64
            runner: 'ubuntu-24.04-arm'
    uses: ./.github/workflows/_job_build.yml
    with:
      name: ${{ matrix.name }}
      cflags: ${{ matrix.cflags }}
      rustflags: ${{ matrix.rustflags }}
      configure: ${{ matrix.configure }}
      runner: ${{ matrix.runner != '' && matrix.runner || 'ubuntu-24.04' }}
      continue: false

  release:
    name: Release
    needs: build
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Create
      id: create
      shell: bash
      run: >-
        gh
        release create
        ${{ github.ref_name }}
        --latest
        --title "${GIT_TAG//Proton-/Proton }"
        --notes-from-tag
        --verify-tag
      env:
        GIT_TAG: ${{ github.ref_name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload:
    name: Upload
    needs: release
    strategy:
      matrix:
        include:
          - name: ${{ github.ref_name }}-x86_64
          - name: ${{ github.ref_name }}-x86_64_v3
          - name: ${{ github.ref_name }}-arm64
    uses: ./.github/workflows/_job_upload.yml
    with:
      version: ${{ github.ref_name }}
      name: ${{ matrix.name }}
